services:
  build:
    image: cypress/browsers:node-22.20.0-chrome-140.0.7339.207-1-ff-143.0.1-edge-140.0.3485.81-1
    container_name: flux-web-components-build
    command: bash $BUILD_SCRIPT
    volumes:
      - ${HOME:-.}/.npmrc:/root/.npmrc:ro
      - ./../..:/flux-web-components
    environment:
      - BAMBOO_BRANCH_NAME=${BAMBOO_BRANCH_NAME:-not-specified}
      - SECRET_GITHUB_TOKEN=${SECRET_GITHUB_TOKEN:-not-specified}
      - ACD_REPOSITORY_DEBIAN_LOGIN=${ACD_REPOSITORY_DEBIAN_LOGIN:-not-specified}
      - ACD_REPOSITORY_BAMBOO_PASSWORD=${ACD_REPOSITORY_BAMBOO_PASSWORD:-not-specified}
      - ACD_REPOSITORY_URL=${ACD_REPOSITORY_URL:-not-specified}
