export const richDataMockData = {
    data: [
        {
            id: 0,
            name: 'Project #1',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Sander', lastName: 'Kleykens' }],
        },
        {
            id: 1,
            name: 'Project #2',
            manager: { firstName: 'Tom', lastName: 'Coemans' },
            medewerkers: [{ firstName: 'Guy', lastName: 'Wauters' }],
        },
        {
            id: 2,
            name: 'Project #3',
            manager: { firstName: 'Tom', lastName: 'Coemans' },
            medewerkers: [{ firstName: 'Guy', lastName: 'Wauters' }],
        },
        {
            id: 3,
            name: 'Project #4',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 4,
            name: 'Project #5',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 5,
            name: 'Project #6',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 6,
            name: 'Project #7',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 7,
            name: 'Project #8',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 8,
            name: 'Project #9',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 9,
            name: 'Project #10',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 10,
            name: 'Project #11',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 11,
            name: 'Project #12',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 12,
            name: 'Project #13',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 13,
            name: 'Project #14',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 14,
            name: 'Project #15',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 15,
            name: 'Project #16',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 16,
            name: 'Project #17',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 17,
            name: 'Project #18',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 18,
            name: 'Project #19',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 19,
            name: 'Project #20',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 20,
            name: 'Project #21',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 21,
            name: 'Project #22',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 22,
            name: 'Project #23',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 23,
            name: 'Project #24',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
        {
            id: 24,
            name: 'Project #25',
            manager: { firstName: 'Pascal', lastName: 'Riquier' },
            medewerkers: [{ firstName: 'Pieter', lastName: 'Beckers' }],
        },
    ],
};
