---
version: 2
plan:
  project-key: FLUX
  key: CFWC
  name: ci-flux-web-components

stages:
  - Build and Test Stage:
      jobs:
        - build-apps-and-libs
        - unit-component-integrator-tests
        - e2e-tests-storybook
  - Release and Publish Stage:
      jobs:
        - release-and-publish
  - Verify Release Stage:
      jobs:
        - verify-release

build-apps-and-libs:
  requirements: &requirements
    - Docker
    - Git
    - REMOTE_ONLY
  tasks:
    - clean
    - script: |
        #!/bin/bash
        # avoid git warning
        git config --global init.defaultBranch develop-v2
    - checkout
    - script: bash ./resources/ci-bamboo/bash/build-apps-and-libs-docker.sh
    - script: &build-artifact |
        # move the folder './build' to './build-artifact/build'
        # this is done so the artifact is shared (in other jobs) in the correct folder (Bamboo 7.2 limitation)
        mkdir build-artifact
        mv build build-artifact
  artifacts:
    - name: artifact-build-apps-and-libs
      location: build-artifact
      pattern: '**/*.*'
      shared: true

unit-component-integrator-tests:
  requirements: *requirements
  tasks:
    - clean
    - script: |
        #!/bin/bash
        # avoid git warning
        git config --global init.defaultBranch develop-v2
    - checkout
    - script: bash ./resources/ci-bamboo/bash/unit-component-integrator-tests-docker.sh
  artifacts:
    - name: artifact-unit-component-integrator-tests
      location: build
      pattern: '**/*.*'

e2e-tests-storybook:
  requirements: *requirements
  tasks:
    - clean
    - script: |
        #!/bin/bash
        # avoid git warning
        git config --global init.defaultBranch develop-v2
    - checkout
    - script: bash ./resources/ci-bamboo/bash/e2e-tests-storybook-docker.sh
  artifacts:
    - name: artifact-e2e-tests-storybook
      location: build
      pattern: '**/*.*'

release-and-publish:
  requirements: *requirements
  tasks:
    - clean
    - script: |
        #!/bin/bash
        # avoid git warning
        git config --global init.defaultBranch develop-v2
    - checkout
    - script: |
        # export variables
        export SECRET_GITHUB_TOKEN=${bamboo.secret_github_token}
        export ACD_REPOSITORY_DEBIAN_LOGIN=${bamboo.acd_repository_debian_login}
        export ACD_REPOSITORY_BAMBOO_PASSWORD=${bamboo.acd_repository_bamboo_password}
        export ACD_REPOSITORY_URL=${bamboo.acd_repository_url}
        # boot the specific docker container
        bash ./resources/ci-bamboo/bash/release-and-publish-docker.sh
  artifacts:
    - name: artifact-release-and-publish
      location: build
      pattern: '**/*.*'

verify-release:
  requirements: *requirements
  tasks:
    - clean
    - script: |
        #!/bin/bash
        # avoid git warning
        git config --global init.defaultBranch develop-v2
    - checkout
    - script: |
        # export variables
        export ACD_REPOSITORY_DEBIAN_LOGIN=${bamboo.acd_repository_debian_login}
        export ACD_REPOSITORY_BAMBOO_PASSWORD=${bamboo.acd_repository_bamboo_password}
        export ACD_REPOSITORY_URL=${bamboo.acd_repository_url}
        # boot the specific docker container
        bash ./resources/ci-bamboo/bash/verify-release-docker.sh
  artifacts:
    - name: artifact-verify-release
      location: build
      pattern: '**/*.*'

---
version: 2
plan:
  key: FLUX-CFWC

plan-permissions:
  - groups: developer-admin
    permissions: build

